I:
  mapping: EKMFLGDQVZNTOWYHXUSPAIBRCJ
  notches:
    - Q
II:
  mapping: AJDKSIRUXBLHWTMCQGZNPYFVOE
  notches:
    - E
III:
  mapping: BDFHJLCPRTXVZNYEIWGAKMUSQO
  notches:
    - V
IV:
  mapping: ESOVPZJAYQUIRHXLNFTGKDCMWB
  notches:
    - J
V:
  mapping: VZBRGITYUPSDNHLXAWMJQOFECK
  notches:
    - Z
VI:
  mapping: JPGVOUMFYQBENHZRDKASXLICTW
  notches:
    - Z
    - M
VII:
  mapping: NZJHGRCXMYSWBOUFAIVLPEKQDT
  notches:
    - Z
    - M
VIII:
  mapping: FKQHTLXOCBJSPDZRAMEWNIUYGV
  notches:
    - Z
    - M
